# Generated by Django 3.2.12 on 2022-04-06 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='discription',
            new_name='description',
        ),
    ]
